---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: n8n

labels:
  - pairs:
      app: n8n
    includeSelectors: true

resources:
  - namespace.yaml
  - secret.yaml
  - configmap.yaml
  - pvc.yaml
  - n8n-deployment.yaml
  - n8n-service.yaml
  - n8n-mcp-deployment.yaml
  - n8n-mcp-service.yaml
